import { dirname, join } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";
import type { CmsConfig, Manifest, ManifestImage } from "./types.js";

const HEADER = `// AUTO-GENERATED by @sea-kers/cms - do not edit.
// Regenerate with: pnpm cms:generate
`;

interface RegistryVariant {
  format: "avif" | "webp" | "jpeg";
  width: number;
  height: number;
  bytes: number;
  uploaded: boolean;
}

interface RegistryRecord {
  id: string;
  collection: string;
  alt: string;
  width: number;
  height: number;
  legacyPath?: string;
  variants: RegistryVariant[];
}

const extensionOf = (path: string): string => {
  const base = path.split("/").pop() ?? "";
  const dot = base.lastIndexOf(".");
  return dot >= 0 ? base.slice(dot + 1) : "jpg";
};

const renderRecord = (image: ManifestImage): RegistryRecord => {
  const record: RegistryRecord = {
    id: image.id,
    collection: image.collection,
    alt: image.alt,
    width: image.width,
    height: image.height,
    variants: image.variants.map((variant) => ({
      format: variant.format,
      width: variant.width,
      height: variant.height,
      bytes: variant.bytes,
      uploaded: variant.uploadedAt !== null,
    })),
  };
  if (image.sourcePath) {
    record.legacyPath = `/images/${image.id}.${extensionOf(image.sourcePath)}`;
  }
  return record;
};

export function renderRegistrySource(manifest: Manifest): string {
  const records = manifest.images
    .filter((image) => image.sourcePath)
    .map(renderRecord);

  const avatarIds: Record<string, string> = {};
  for (const image of manifest.images) {
    if (
      image.collection === "team" &&
      image.ref &&
      image.variants.some((variant) => variant.uploadedAt)
    ) {
      avatarIds[image.ref] = image.id;
    }
  }

  const recordsByKey: Record<string, RegistryRecord> = Object.fromEntries(
    records.map((record) => [record.id, record]),
  );
  const recordsJson = JSON.stringify(recordsByKey, null, 2);
  const avatarJson = JSON.stringify(avatarIds, null, 2);
  const baseUrl = JSON.stringify(manifest.baseUrl);

  return `${HEADER}
export const IMAGE_BASE_URL = ${baseUrl};

export type ImageFormat = "avif" | "webp" | "jpeg";

export interface ImageVariant {
  format: ImageFormat;
  width: number;
  height: number;
  bytes: number;
  uploaded: boolean;
}

export interface ImageRecord {
  id: string;
  collection: string;
  alt: string;
  width: number;
  height: number;
  legacyPath?: string;
  variants: ImageVariant[];
}

export const IMAGE_REGISTRY: Record<string, ImageRecord> = ${recordsJson};

export const TEAM_AVATAR_IDS: Record<string, string> = ${avatarJson};

export const getImageRecord = (id: string): ImageRecord | undefined =>
  IMAGE_REGISTRY[id];

export const imageUrl = (id: string, width: number, format: ImageFormat): string =>
  \`\${IMAGE_BASE_URL}/\${id}-\${width}.\${format}\`;
`;
}

export function writeRegistry(config: CmsConfig, manifest: Manifest): string {
  const outputPath = join(config.projectPath, config.registryOut);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderRegistrySource(manifest), "utf8");
  return outputPath;
}
